---
kind: pipeline
name: default

steps:
  - name: build
    image: golang:1.12-alpine
    commands:
      - GOOS=linux CGO_ENABLED=0 go build -ldflags="-s -w" -o instant-access main.go
    when:
      event:
        - tag

  - name: build-image
    image: plugins/docker
    settings:
      username: erguotou
      password:
        from_secret: docker_pwd
      repo: erguotou/drone-instant-access
      auto_tag: true
    when:
      event:
        - tag

  - name: sendmsg
    image: erguotou/drone-instant-access
    settings:
      channel:
        from_secret: serverchan_key
      head: succeeded
      body: docker build erguotou/drone-instant-access
    when:
      event:
        - tag